encoding: utf-8

# seo
title: DanWang Blog
description: DanWang Blog
keywords: DanWang,Blog,Java,C#,SQL Server,MySQL,Machine Learning,Collaborative Filtering,Js,算法
author: DanWang

# "","/blog"
context: ""
"siteMapPrefix": "https://anndwang.github.io/"

## 文章url前缀 context/自定义，下面的context为''
permalink: /posts/:year/:month/:day/:title.html

copyright: 2018
record: ""

coderay:
  coderay_tab_width: 4
  
markdown: kramdown
kramdown:
  input:  GFM
  use_coderay: true